/**
 * useUserRepository - Generated by Garanteasier CLI
 */

import { useSQLiteContext } from "expo-sqlite";

export function useUserRepository() {
  const db = useSQLiteContext();
  async function getUser() {
    const query = `SELECT * FROM owners LIMIT 1`;
    const result = await db.getFirstAsync(query);
    return result ? result : null;
  }
  return {
    getUser
  };
}
