/**
 * useUserRepository - Generated by Garanteasier CLI
 */

import { useSQLiteContext } from "expo-sqlite";
import { useCallback } from "react";

export function useUserRepository() {
  const db = useSQLiteContext();

  const getUser = useCallback(async () => {
    const query = `SELECT * FROM owners LIMIT 1`;
    const result = await db.getFirstAsync(query);
    return result ? result : null;
  }, [db]);

  return {
    getUser
  };
}
