/**
 * FormCard - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import FormCard from "../index";

describe("FormCard Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<FormCard />).toJSON();
      expect(tree).toMatchSnapshot();
    });
});