/**
 * IGDropdown2Props - Generated by Garanteasier CLI
 */

import { HistoryLabel } from "../../../models/History/History";

export interface InterventionDropdownProps {
  style?: object;
  testID?: string;
  onValueChange?: (value: HistoryLabel) => void;
}