/**
 * InterventionDropdown - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import InterventionDropdown from "./index";

export default {
  title: 'InterventionDropdown',
  component: InterventionDropdown
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <InterventionDropdown />
    </View>
);