/**
 * GDropdown2 - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import GDropdown2 from "./index";

export default {
  title: 'GDropdown2',
  component: GDropdown2
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <GDropdown2 />
    </View>
);