/**
* AddIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 15,
  color: COLORS.primary,
};

// TODO: create tests for this AddIcon component
function AddIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path d="M6.5 8.5h-6v-2h6v-6h2v6h6v2h-6v6h-2v-6z" fill={color} />
    </Svg>
  );
}

export default AddIcon;
