/**
* BellIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 16,
  color: COLORS.light,
};

function BellIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path
        d="M4 12.666v-6a4 4 0 118 0v6m-8 0h8m-8 0H2.667m9.333 0h1.333m-6 2h1.334"
        stroke={color}
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <Path
        d="M8 2.666a.667.667 0 100-1.333.667.667 0 000 1.333z"
        stroke={color}
        strokeWidth={2}
      />
    </Svg>
  );
}

export default BellIcon;
