/**
* BookIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { useDynamicSize } from "../../../hooks/useDynamicSize";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  width: 16,
  height: 14,
  color: COLORS.light,
};

function BookIcon ({
  size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  const { width, height } = useDynamicSize(
        DEFAULT_PROPS.width,
        DEFAULT_PROPS.height,
        size
          ? size
          : DEFAULT_PROPS.width);
  return (
    <Svg
      width={width}
      height={height}
      viewBox={`0 0 ${DEFAULT_PROPS.width} ${DEFAULT_PROPS.height}`}
      fill="none"
      {...props}
    >
      <Path
        d="M1.333 3.667c0-.934 0-1.4.182-1.757.16-.314.415-.569.728-.729C2.6 1 3.067 1 4 1c.933 0 1.4 0 1.757.181.313.16.569.415.728.729.182.357.182.823.182 1.757m-5.334 0v6.666c0 .934 0 1.4.182 1.757.16.313.415.568.728.728C2.6 13 3.067 13 4 13c.933 0 1.4 0 1.757-.182.313-.16.568-.415.728-.728.182-.357.182-.823.182-1.757V3.667m-5.334 0h5.334M4 10.333h.006m7.848-.203l.006-.001M8 4.333L12.333 3m-4.7 1.512c-.237-.887-.356-1.33-.274-1.715a1.64 1.64 0 01.504-.877c.292-.263.734-.382 1.616-.62.883-.237 1.325-.356 1.708-.274.337.072.643.25.873.507.263.292.381.735.618 1.622l1.69 6.333c.236.887.355 1.33.273 1.715a1.64 1.64 0 01-.504.877c-.292.263-.734.382-1.616.62-.883.237-1.324.356-1.708.274a1.633 1.633 0 01-.873-.507c-.263-.292-.381-.735-.618-1.622l-1.69-6.333z"
        stroke={color}
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export default BookIcon;
