/**
* CalendarIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 24,
  color: COLORS.primary,
};

// TODO: create tests for this CalendarIcon component
function CalendarIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path
        d="M16 1.25c.41 0 .75.34.75.75v1.25H19c1.52 0 2.75 1.23 2.75 2.75v14c0 1.52-1.23 2.75-2.75 2.75H5c-1.52 0-2.75-1.23-2.75-2.75V6c0-1.52 1.23-2.75 2.75-2.75h2.25V2c0-.41.34-.75.75-.75s.75.34.75.75v1.25h6.5V2c0-.41.34-.75.75-.75zm-12.25 9.5V20c0 .69.56 1.25 1.25 1.25h14c.69 0 1.25-.56 1.25-1.25v-9.25H3.75zm1.25-6c-.69 0-1.25.56-1.25 1.25v3.25h16.5V6c0-.69-.56-1.25-1.25-1.25h-2.25V6a.749.749 0 11-1.5 0V4.75h-6.5V6a.749.749 0 11-1.5 0V4.75H5z"
        fill={color}
      />
    </Svg>
  );
}

export default CalendarIcon;
