/**
* CheckIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { useDynamicSize } from "../../../hooks/useDynamicSize";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  width: 22,
  height: 16,
  color: COLORS.light,
};

// TODO: create tests for this CheckIcon component
function CheckIcon ({
  color = DEFAULT_PROPS.color, size, ...props
}: IconProps) {
  const { width, height } = useDynamicSize(
      DEFAULT_PROPS.width,
      DEFAULT_PROPS.height,
      size
        ? size
        : DEFAULT_PROPS.width);
  return (
    <Svg
      width={width}
      height={height}
      viewBox={`0 0 ${DEFAULT_PROPS.width} ${DEFAULT_PROPS.height}`}
      fill="none"
      {...props}
    >
      <Path
        d="M20 2L7.625 14 2 8.545"
        stroke={color}
        strokeWidth={3}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export default CheckIcon;
