/**
* CloseIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 39,
  color: COLORS.primary,
};

// TODO: create tests for this CloseIcon component
function CloseIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path
        d="M4.3 38L.5 34.2 15.7 19 .5 3.8 4.3 0l15.2 15.2L34.7 0l3.8 3.8L23.3 19l15.2 15.2-3.8 3.8-15.2-15.2L4.3 38z"
        fill={color}
      />
    </Svg>
  );
}

export default CloseIcon;
