/**
* PictureIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 40,
  color: COLORS.primary,
};

function PictureIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path
        d="M6.5 38h28a4 4 0 004-4V6a4 4 0 00-4-4h-28a4 4 0 00-4 4v28a4 4 0 004 4zm0 0l22-22 10 10m-22-13a3 3 0 11-6 0 3 3 0 016 0z"
        stroke={color}
        strokeWidth={3.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export default PictureIcon;
