/**
* QuestionMarkIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 24,
  color: COLORS.black,
};

// TODO: create tests for this QuestionMarkIcon component
function QuestionMarkIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path
        d="M12 19h.01M8.217 7.697A4.002 4.002 0 0116 9a4.001 4.001 0 01-2.442 3.685c-.74.314-1.111.47-1.24.592a.75.75 0 00-.257.386C12 13.83 12 14.087 12 14.6V16"
        stroke="#000"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export default QuestionMarkIcon;
