/**
* TrashIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  size: 25,
  color: COLORS.primary,
};

// TODO: create tests for this TrashIcon component
function TrashIcon ({
  size = DEFAULT_PROPS.size,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox={`0 0 ${DEFAULT_PROPS.size} ${DEFAULT_PROPS.size}`}
      fill="none"
      {...props}
    >
      <Path
        d="M7.75 21.5c-.55 0-1.02-.196-1.412-.587A1.926 1.926 0 015.75 19.5v-13h-1v-2h5v-1h6v1h5v2h-1v13c0 .55-.196 1.02-.587 1.413a1.926 1.926 0 01-1.413.587h-10zm10-15h-10v13h10v-13zm-8 11h2v-9h-2v9zm4 0h2v-9h-2v9z"
        fill={color}
      />
    </Svg>
  );
}

export default TrashIcon;
