/**
* UploadIcon - Generated by Garanteasier CLI
*/

import * as React from "react";
import Svg, { Path } from "react-native-svg";
import { COLORS } from "../../../constants";
import { useDynamicSize } from "../../../hooks/useDynamicSize";
import { IconProps } from "./@types";

const DEFAULT_PROPS = {
  width: 32,
  height: 34,
  color: COLORS.light,
};

// TODO: create tests for this UploadIcon component
function UploadIcon ({
  size = DEFAULT_PROPS.width,
  color = DEFAULT_PROPS.color,
  ...props
}: IconProps) {
  const { width, height } = useDynamicSize(
      DEFAULT_PROPS.width,
      DEFAULT_PROPS.height,
      size
        ? size
        : DEFAULT_PROPS.width);
  return (
    <Svg
      width={width}
      height={height}
      viewBox={`0 0 ${DEFAULT_PROPS.width} ${DEFAULT_PROPS.height}`}
      fill="none"
      {...props}
    >
      <Path
        d="M28 21.128v5.47c0 .726-.281 1.421-.781 1.934-.5.513-1.178.801-1.886.801H6.667a2.633 2.633 0 01-1.886-.8A2.771 2.771 0 014 26.597v-5.47M22.667 11.556L16 4.718l-6.667 6.838M16 4.718v16.41"
        stroke={color}
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export default UploadIcon;
