/**
 * useSettingRepository - Generated by Garanteasier CLI
 */

import { useSQLiteContext } from "expo-sqlite";
import React from "react";
import { Setting } from "../../models/Setting/Setting";
import { EKeySetting, SettingDto } from "../../models/Setting/Setting.dto";

/**
 * useSettingRepository
 * A custom hook that provides methods to interact with the settings repository.
 * It allows fetching settings by their key from the SQLite database.
 */
export function useSettingRepository() {
  const db = useSQLiteContext();

  /**
   * getSettingByKey
   * Fetch a setting by its key from the database.
   * @param key - The key of the setting to fetch.
   * @returns A promise that resolves to the Setting object.
   * @throws An error if the setting is not found or if the database connection is not established.
   */
  const getSettingByKey = React.useCallback(async (key: EKeySetting) => {
    const setting = await db.getFirstAsync<SettingDto>(`SELECT * FROM settings WHERE key = ?`, [key]);
    if (!setting) {
      throw new Error(`Setting with key ${key} not found`);
    }
    return Setting.toModel<SettingDto, Setting>(setting);
  }, [db]);

  const getAllSettings = React.useCallback(async (): Promise<Setting[]> => {
    const settings = await db.getAllAsync<SettingDto>(`SELECT * FROM settings`);
    return settings.map(setting => Setting.toModel<SettingDto, Setting>(setting));
  }, [db]);

  const updateSettingByKey = React.useCallback(async (key: EKeySetting, value: string) => {
    const result = await db.runAsync(`UPDATE settings SET value = ? WHERE key = ?`, [value, key]);
    if (result.changes === 0) {
      throw new Error(`Setting with key ${key} not found`);
    }
  }, [db]);

  return {
    getSettingByKey,
    getAllSettings,
    updateSettingByKey
  };
}
