/**
 * SwitchButton - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import SwitchButton from "../index";

describe("SwitchButton Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<SwitchButton
        value={false}
        onValueChange={() => { }}
      />).toJSON();
      expect(tree).toMatchSnapshot();
    });
});