/**
 * RoundedIconButton - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import RoundedIconButton from "../index";

describe("RoundedIconButton Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<RoundedIconButton icon="arrow-left" onPress={() => {}} />).toJSON();
      expect(tree).toMatchSnapshot();
    });
});