/**
 * GTextInput - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import GTextInput from "../index";

describe("GTextInput Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<GTextInput label="Test" />).toJSON();
      expect(tree).toMatchSnapshot();
    });
});