/**
 * ProductCard - Generated by Garanteasier CLI
 */

import React from "react";
import { View, Text, Image } from "react-native";
import { DateService } from "../../../services/DateService";
import ProgressIndicator from "../ProgressIndicator";
import RoundedIconButton from "../RoundedIconButton";
import Tag from "../Tag";
import { IProductCardProps } from "./@types";
import ProductCardStyles from "./styles";

const ProductCard: React.FC<IProductCardProps> = ({ style, testID = 'productcard', purchaseDate, onPress, ...props }) => {

  const [warrantyDurationTag, setWarrantyDurationTag] = React.useState<string>('');
  const [progress, setProgress] = React.useState<number>(1);

  // Debug image prop
  React.useEffect(() => {
    if (props.image) {
      console.log('ProductCard image prop:', props.image);
      console.log('Image type:', typeof props.image);
    }
  }, [props.image]);

  // Helper function to determine the correct image source
  const getImageSource = () => {
    if (!props.image) {
      return require('../../../assets/images/default-product.png');
    }

    if (typeof props.image === 'string') {
      // Check if it's a file URI or HTTP URL
      if (props.image.startsWith('file://') || props.image.startsWith('http://') || props.image.startsWith('https://')) {
        return { uri: props.image };
      }
      // If it's just a string, assume it's a require() path
      return props.image;
    }

    // If it's already an object (like {uri: string}), use it directly
    return props.image;
  };

  function formatExpirationDate(purchaseDateProp: Date | string, warrantyDurationInDays: number): string {
    const _purchaseDate = new Date(purchaseDateProp);
    const expirationDate = DateService.addDays(_purchaseDate, warrantyDurationInDays);
    const currentDate = new Date(); // Use the current date for calculations

    if (DateService.IsDateAfter(currentDate, expirationDate)) {
      return `Expiré le ${DateService.formatMMYY(expirationDate)}`;
    }

    // Calculate days left from the current date to the expiration date
    const daysLeft = DateService.getDaysBetweenDates(currentDate, expirationDate);

    if (daysLeft > 365) {
      const yearsLeft = Math.floor(daysLeft / 365);
      return `Expire dans ${yearsLeft}an${yearsLeft > 1 ? 's' : ''}`;
    }
    if (daysLeft > 99) {
      const monthsLeft = Math.floor(daysLeft / 30);
      return `Expire dans ${monthsLeft}m`;
    }
    return `Expire dans ${daysLeft}j`;
  }

  React.useEffect(() => {
    if (props.warrantyDuration) {
      const warrantyDurationInDays = DateService.getWarrantyDurationInDays(props.warrantyDuration);
      const expirationDate = formatExpirationDate(purchaseDate, warrantyDurationInDays);
      setWarrantyDurationTag(expirationDate);

      // Calculate rest days from purchase date to expiration date
      const _purchaseDate = new Date(purchaseDate);
      const expirationDateObj = DateService.addDays(_purchaseDate, warrantyDurationInDays);
      const currentDate = new Date();

      if (DateService.IsDateAfter(currentDate, expirationDateObj)) {
        setProgress(0);
      }
      else if (DateService.IsDateAfter(currentDate, _purchaseDate)) {
        const totalDays = DateService.getDaysBetweenDates(_purchaseDate, expirationDateObj);
        const daysPassed = DateService.getDaysBetweenDates(_purchaseDate, currentDate);

        setProgress(1 - (daysPassed / totalDays));
      }
      else {
        setProgress(1);
      }

    } else {
      setWarrantyDurationTag('Aucune garantie');
    }
  }, [props.warrantyDuration, purchaseDate]);

  return (
      <View style={[ProductCardStyles.container, style]} testID={testID} {...props}>
        <Image
          source={getImageSource()}
          style={ProductCardStyles.image}
          resizeMode="cover"
          onError={(error) => {
            console.error('ProductCard Image load error:', error.nativeEvent.error);
            console.log('Failed image source:', getImageSource());
          }}
        />
        <View style={{ display: 'flex', flex: 1 }}>
          <View style={ProductCardStyles.brandContainer}>
            <Text style={ProductCardStyles.name} numberOfLines={1}>
              {props.name || 'Product Name'}
            </Text>
            {onPress && <RoundedIconButton icon="arrow-right" onPress={() => onPress()} size="small" />}
          </View>
          <Text style={ProductCardStyles.brand} numberOfLines={1}>
            {props.brand || 'Brand Name'}
          </Text>
          <View style={ProductCardStyles.tags}>
            <Tag testID="test-tag-1" label={`Acheté le: ${DateService.formatMMYY(purchaseDate)}`} textStyle={ProductCardStyles.tagsText} />
            <Tag testID="test-tag-2" label={warrantyDurationTag} textStyle={ProductCardStyles.tagsText} />
        </View>
        <ProgressIndicator value={progress} />
        </View>
      </View>
  );
};

export default ProductCard;
