/**
 * ProductCard - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import { DateService } from "../../../services/DateService";
import ProductCard from "./index";

export default {
  title: 'ProductCard',
  component: ProductCard
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 8, gap: 16 }}>
    <ProductCard
      brand="Bosh"
      name="Tondeuse à gazon"
      purchaseDate={DateService.subtractDays(new Date(), 3)}
      warrantyDuration="15d"
      image={require('../../../assets/images/default-product.png')}
    />
    <ProductCard
      brand="Bosh"
      name="Tondeuse à gazon"
      purchaseDate={DateService.subtractDays(new Date(), 3)}
      warrantyDuration="2m7j"
      image={require('../../../assets/images/default-product.png')}
    />
    <ProductCard
      brand="Bosh"
      name="Tondeuse à gazon"
      purchaseDate={DateService.subtractDays(new Date(), 8)}
      warrantyDuration="15d"
      image={require('../../../assets/images/default-product.png')}
    />
    <ProductCard
      brand="Bosh"
      name="Tondeuse à gazon"
      purchaseDate={DateService.subtractDays(new Date(), 11)}
      warrantyDuration="15d"
      image={require('../../../assets/images/default-product.png')}
    />
    </View>
);