/**
 * IGTextInputProps - Generated by Garanteasier CLI
 */

import { StyleProp, TextInputProps, TextStyle, ViewStyle } from "react-native";

export interface IGTextInputProps extends TextInputProps {
  containerStyle?: StyleProp<ViewStyle>;
  labelStyle?: StyleProp<TextStyle>;
  label: string;
  testID?: string;

}