/**
 * GTextInput - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import GTextInput from "./index";

export default {
  title: 'GTextInput',
  component: GTextInput
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <GTextInput />
    </View>
);