/**
 * GTextInput - Generated by Garanteasier CLI
 */

import React from "react";
import { View, Text, TextInput } from "react-native";
import { IGTextInputProps } from "./@types";
import GTextInputStyles from "./styles";

const GTextInput: React.FC<IGTextInputProps> = ({style, containerStyle, labelStyle, testID = 'gtextinput', label, ...props}) => {
  return (
    <View style={[GTextInputStyles.container, containerStyle]} testID={testID}>
      <Text style={[GTextInputStyles.label, labelStyle]}>{label}</Text>
      <TextInput
        {...props}
        style={[GTextInputStyles.textInput, style]}
      />
    </View>
  );
};

export default GTextInput;
