/**
 * GTextInputStyles - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../../../constants';

const styles = StyleSheet.create({
  container: {
    marginVertical: 5,
  },
  label: {
    marginBottom: 5,
    color: COLORS.placeholder,
    fontSize: 14,
    fontFamily: SIZES.font.familly.default,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 4,
    padding: 10,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#fff',
  }
});

export default styles;
