/**
 * RoundedIconButton - Generated by Garanteasier CLI
 */

export interface IRoundedIconButtonProps {
  style?: object;
  size?: IRoundedIconButtonSize;
  testID?: string;
  icon: IRoundedIconButtonType;
  onPress: () => void;
}

export type IRoundedIconButtonType = 'scan' | 'settings' | 'arrow-left' | 'arrow-right' | 'upload' | 'close';

export type IRoundedIconButtonSize = 'normal' | 'small' | 'big';
