/**
 * RoundedIconButton - Generated by Garanteasier CLI
 */

export interface IRoundedIconButtonProps {
  style?: object;
  testID?: string;
  icon: IRoundedIconButtonType;
  onPress: () => void;
}

export type IRoundedIconButtonType = 'scan' | 'settings' | 'arrow-left' | 'arrow-right'
