/**
 * RoundedIconButton - Generated by Garanteasier CLI
 */

import React from "react";
import { Text, TouchableOpacity } from "react-native";
import { IRoundedIconButtonProps } from "./@types";
import RoundedIconButtonStyles from "./styles";

const RoundedIconButton: React.FC<IRoundedIconButtonProps> = ({ style, testID = 'roundediconbutton', ...props }) => {
  function getIconComponent(icon: IRoundedIconButtonProps['icon']) {
    switch (icon) {
      case 'scan':
        return <Text>Scan Icon</Text>;
      case 'settings':
        return <Text>Settings Icon</Text>;
      case 'arrow-left':
        return <Text>Arrow Left Icon</Text>;
      case 'arrow-right':
        return <Text>Arrow Right Icon</Text>;
      default:
        return <Text>Default Icon</Text>;
    }
  }
  return (
    <TouchableOpacity style={[RoundedIconButtonStyles, style]} testID={testID} {...props}>
      {getIconComponent(props.icon)}
    </TouchableOpacity>
  );
};

export default RoundedIconButton;
