/**
 * RoundedIconButton - Generated by Garanteasier CLI
 */

import React from "react";
import { TouchableOpacity } from "react-native";
import ArrowIcon from "../Icons/ArrowIcon";
import ScanIcon from "../Icons/ScanIcon";
import SettingsIcon from "../Icons/SettingsIcon";
import { IRoundedIconButtonProps } from "./@types";
import RoundedIconButtonStyles from "./styles";

const RoundedIconButton: React.FC<IRoundedIconButtonProps> = ({ style, testID = 'roundediconbutton', icon, size = 'normal', ...props }) => {
  const iconComponent = React.useMemo(() => {
    switch (icon) {
      case 'scan':
        return <ScanIcon />;
      case 'settings':
        return <SettingsIcon />;
      case 'arrow-left':
        return <ArrowIcon />;
      case 'arrow-right':
        return <ArrowIcon style={{ transform: [{ scaleX: -1 }] }}/>;
      default:
        return <ScanIcon />;
    }
  }, [icon]);
  return (
    <TouchableOpacity style={[RoundedIconButtonStyles(size).container, style]} testID={testID} {...props}>
      {iconComponent}
    </TouchableOpacity>
  );
};

export default RoundedIconButton;
