/**
 * RoundedIconButton - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import RoundedIconButton from "./index";

export default {
  title: 'RoundedIconButton',
  component: RoundedIconButton
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <RoundedIconButton icon="arrow-left" onPress={() => {}} />
    </View>
);