/**
 * {{ElementComponent}} - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../../../constants';
import { IRoundedIconButtonSize } from './@types';

function getSize(size: IRoundedIconButtonSize): number {
  if (size === 'normal') {
    return 40;
  }
if (size === 'small') {
    return 32;
  }
  if (size === 'big') {
    return 70;
  }
  return 40; // Default case
}

const styles = function getRoundedIconButtonStyle(size: IRoundedIconButtonSize) {
  return StyleSheet.create({
    container: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'column',
      backgroundColor: COLORS.primary,
      borderRadius: SIZES.radius.full,
      height: getSize(size),
      width: getSize(size),
    }
  });
};

export default styles;
