/**
 * useOnboardingRepository - Generated by Garanteasier CLI
 */

import { useSQLiteContext } from "expo-sqlite";
import React from "react";
import { Onboarding, OnboardingDto } from "../../constants/Onboardings";

export function useOnboardingRepository() {
  const db = useSQLiteContext();

  const getMostRecentOnboarding = React.useCallback(async (): Promise<Onboarding | null> => {
    const query = `SELECT * FROM onboardings ORDER BY created_at DESC LIMIT 1`;
    const result = await db.getFirstAsync<OnboardingDto>(query);
    if (result) {
      // Marquer tous les autres onboarding comme terminés
      const updateQuery = `UPDATE onboardings SET is_completed = 1 WHERE name != ?`;
      const prepare = await db.prepareAsync(updateQuery);
      await prepare.executeAsync([result.name]);
      return Onboarding.fromDto(result);
    }
    return null;
  }, [db]);

  const markOnboardingAsCompleted = React.useCallback(async (onboardingName: string): Promise<void> => {
    const updateQuery = `UPDATE onboardings SET is_completed = 1 WHERE name = ?`;
    const prepare = await db.prepareAsync(updateQuery);
    await prepare.executeAsync([onboardingName]);
  }, [db]);

  return {
    getMostRecentOnboarding,
    markOnboardingAsCompleted
  };
}
