/**
 * IFormCardProps - Generated by Garanteasier CLI
 */

import { PropsWithChildren } from "react";

export interface IFormCardProps extends PropsWithChildren {
  style?: object;
  testID?: string;
}