/**
 * FormCard - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import FormCard from "./index";

export default {
  title: 'FormCard',
  component: FormCard
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <FormCard />
    </View>
);