/**
 * FormCardStyles - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants';

const styles = StyleSheet.create({
  container: {
    gap: 10,
    backgroundColor: COLORS.greyLighter,
    borderColor: COLORS.greyDarker,
    borderWidth: 1,
    padding: 16,
    borderRadius: 8,
  }
});

export default styles;
