/**
 * ProgressIndicator - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import { IProgressIndicatorProps } from "./@types";
import ProgressIndicatorStyles from "./styles";

const ProgressIndicator: React.FC<IProgressIndicatorProps> = ({ style, testID = 'progressindicator', value, ...props }) => {
  const progressIndicatorStyles = ProgressIndicatorStyles({ percent: value });
  return (
    <View style={[progressIndicatorStyles.container, style]} testID={testID} {...props} />
  );
};

export default ProgressIndicator;
