/**
 * {{ElementComponent}} - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../../../constants';

export interface IProgresIndicatorStyle {
  percent: number;
}

const styles = function ({ percent }: IProgresIndicatorStyle) {
  function getColorStyles(amount: number): string {
    if (percent <= 1 && percent >= 0.5) return COLORS.success;
    if (percent < 0.5 && percent >= 0.25) return COLORS.warning;
    return COLORS.dangerLight;
  }
  return StyleSheet.create({
    container: {
      borderRadius: SIZES.radius.full,
      height: 8,
      width: `${percent * 100}%`,
      backgroundColor:  getColorStyles(percent),
  }
}); };

export default styles;
