/**
 * InterventionDropdown - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import InterventionDropdown from "../index";

describe("InterventionDropdown Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<InterventionDropdown />).toJSON();
      expect(tree).toMatchSnapshot();
    });
});