/**
 * IGDateInputProps - Generated by Garanteasier CLI
 */

import { StyleProp, TextInputProps, TextStyle, ViewStyle } from "react-native";

export interface IGDateInputProps extends TextInputProps {
  style?: object;
  testID?: string;
  containerStyle?: StyleProp<ViewStyle>;
  labelStyle?: StyleProp<TextStyle>;
  errorStyle?: StyleProp<TextStyle>;
  label: string;
  value?: string; // Default value in DD/MM/YYYY format
  allowFutureDates?: boolean;
  onDateValidation?: (isValid: boolean, errorMessage?: string) => void;
  onDateChange?: (date: Date) => void;
}