/**
 * GDateInput - Generated by Garanteasier CLI
 */

import React from "react";
import { View } from "react-native";
import GDateInput from "./index";

export default {
  title: 'GDateInput',
  component: GDateInput
};

export const Default = () => (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <GDateInput />
    </View>
);