/**
 * GDateInputStyles - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants';

const styles = StyleSheet.create({
  label: {
      marginBottom: 5,
      color: COLORS.placeholder,
      fontSize: 14,
    },
    textInput: {
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 4,
      padding: 10,
      fontSize: 16,
      color: '#333',
      backgroundColor: '#fff',
    },
    textInputError: {
      borderColor: '#ff4444',
    },
    errorText: {
      color: '#ff4444',
      fontSize: 12,
      marginTop: 5,
    }
});

export default styles;
