/**
 * GDateInputStyles - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants';

const styles = StyleSheet.create({
  label: {
      marginBottom: 5,
      color: COLORS.placeholder,
      fontSize: 14,
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 4,
    backgroundColor: '#fff',
    gap: 10,
    paddingHorizontal: 10,
  },
  textInput: {
    fontSize: 16,
    paddingVertical: 10,
    color: '#333',
    flex: 1,
  },
  textInputError: {
    borderColor: '#ff4444',
  },
  errorText: {
    color: '#ff4444',
    fontSize: 12,
    marginTop: 5,
  }
});

export default styles;
