/**
 * ISwitchButtonProps - Generated by Garanteasier CLI
 */

import { ViewStyle } from 'react-native';

export interface ISwitchButtonProps {
  /**
   * The current value of the switch
   */
  value: boolean;

  /**
   * Callback function called when the switch value changes
   */
  onValueChange: (value: boolean) => void;

  /**
   * Optional label to display next to the switch
   */
  label?: string;

  /**
   * Position of the label relative to the switch
   */
  labelPosition?: 'left' | 'right';

  /**
   * Disable the switch
   */
  disabled?: boolean;

  /**
   * Size of the switch
   */
  size?: 'small' | 'medium' | 'large';

  /**
   * Custom colors for the switch
   */
  colors?: {
    active?: string;
    inactive?: string;
    thumb?: string;
    disabledActive?: string;
    disabledInactive?: string;
  };

  /**
   * Custom style for the container
   */
  style?: ViewStyle;

  /**
   * Test ID for testing purposes
   */
  testID?: string;
}