/**
 * SwitchButton - Generated by Garanteasier CLI
 */

import React, { useRef, useEffect } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  Animated,
  Easing,
} from "react-native";
import { ISwitchButtonProps } from "./@types";
import styles from "./styles";

const SwitchButton: React.FC<ISwitchButtonProps> = ({
  value,
  onValueChange,
  label,
  labelPosition = 'right',
  disabled = false,
  size = 'medium',
  colors,
  style,
  testID = 'switchbutton',
  ...props
}) => {
  const translateX = useRef(new Animated.Value(value ? 1 : 0)).current;

  // Animation when value changes
  useEffect(() => {
    const toValue = value ? 1 : 0;

    Animated.timing(translateX, {
      toValue,
      duration: 200,
      easing: Easing.bezier(0.4, 0.0, 0.2, 1),
      useNativeDriver: true,
    }).start();
  }, [value, translateX]);

  // Handle press
  const handlePress = () => {
    if (disabled) return;
    onValueChange(!value);
  };

  // Get size-specific styles
  const getSizeStyles = () => {
    switch (size) {
      case 'small':
        return {
          switch: styles.switchSmall,
          thumb: styles.thumbSmall,
          translateDistance: 16, // 40 - 24 (switch width - thumb width)
        };
      case 'large':
        return {
          switch: styles.switchLarge,
          thumb: styles.thumbLarge,
          translateDistance: 24, // 56 - 32
        };
      default: // medium
        return {
          switch: styles.switchMedium,
          thumb: styles.thumbMedium,
          translateDistance: 20, // 48 - 28
        };
    }
  };

  // Get background color
  const getBackgroundColor = () => {
    if (disabled) {
      return value
        ? (colors?.disabledActive || styles.switchDisabledActive.backgroundColor)
        : (colors?.disabledInactive || styles.switchDisabledInactive.backgroundColor);
    }

    return value
      ? (colors?.active || styles.switchActive.backgroundColor)
      : (colors?.inactive || styles.switchInactive.backgroundColor);
  };

  // Get thumb color
  const getThumbColor = () => {
    if (disabled) {
      return styles.thumbDisabled.backgroundColor;
    }
    return colors?.thumb || styles.thumbMedium.backgroundColor;
  };

  const sizeStyles = getSizeStyles();

  // Calculate thumb position
  const thumbTransform = {
    transform: [
      {
        translateX: translateX.interpolate({
          inputRange: [0, 1],
          outputRange: [0, sizeStyles.translateDistance],
        }),
      },
    ],
  };

  const renderLabel = () => {
    if (!label) return null;

    return (
      <Text
        style={[
          styles.labelText,
          disabled && styles.labelTextDisabled,
        ]}
      >
        {label}
      </Text>
    );
  };

  return (
    <View style={[styles.container, style]} testID={testID} {...props}>
      {labelPosition === 'left' && (
        <View style={styles.labelLeft}>
          {renderLabel()}
        </View>
      )}

      <TouchableOpacity
        onPress={handlePress}
        disabled={disabled}
        activeOpacity={0.8}
        accessibilityRole="switch"
        accessibilityState={{
          checked: value,
          disabled: disabled
        }}
        accessibilityLabel={label}
        testID={`${testID}-switch`}
      >
        <View
          style={[
            sizeStyles.switch,
            { backgroundColor: getBackgroundColor() },
          ]}
        >
          <Animated.View
            style={[
              sizeStyles.thumb,
              { backgroundColor: getThumbColor() },
              thumbTransform,
            ]}
          />
        </View>
      </TouchableOpacity>

      {labelPosition === 'right' && (
        <View style={styles.labelRight}>
          {renderLabel()}
        </View>
      )}
    </View>
  );
};

export default SwitchButton;
