/**
 * SwitchButtonStyles - Generated by Garanteasier CLI
 */

import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants/Colors';

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  labelLeft: {
    marginRight: 12,
  },

  labelRight: {
    marginLeft: 12,
  },

  labelText: {
    fontSize: 16,
    color: COLORS.placeholder,
    fontWeight: '500',
  },

  labelTextDisabled: {
    color: COLORS.greyDarker,
  },

  // Small size
  switchSmall: {
    width: 40,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    padding: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },

  thumbSmall: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },

  // Medium size (default)
  switchMedium: {
    width: 48,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    padding: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },

  thumbMedium: {
    width: 20,
    height: 20,
    borderRadius: 12,
    backgroundColor: COLORS.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },

  // Large size
  switchLarge: {
    width: 56,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    padding: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },

  thumbLarge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },

  // Active states
  switchActive: {
    backgroundColor: COLORS.primary,
  },

  switchInactive: {
    backgroundColor: COLORS.greyDarker,
  },

  // Disabled states
  switchDisabledActive: {
    backgroundColor: COLORS.greyLighter,
  },

  switchDisabledInactive: {
    backgroundColor: COLORS.greyLighter,
  },

  thumbDisabled: {
    backgroundColor: COLORS.grey,
  },
});

export default styles;
