/**
 * SwitchButton - Generated by Garanteasier CLI
 */

import React, { useState } from "react";
import { View } from "react-native";
import SwitchButton from "./index";

export default {
  title: 'SwitchButton',
  component: SwitchButton
};

export const Default = () => {
  const [isEnabled, setIsEnabled] = useState(false);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <SwitchButton
        value={isEnabled}
        onValueChange={setIsEnabled}
        label="Activer les notifications"
      />
    </View>
  );
};

export const WithoutLabel = () => {
  const [isEnabled, setIsEnabled] = useState(true);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <SwitchButton
        value={isEnabled}
        onValueChange={setIsEnabled}
      />
    </View>
  );
};

export const LabelLeft = () => {
  const [isEnabled, setIsEnabled] = useState(false);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <SwitchButton
        value={isEnabled}
        onValueChange={setIsEnabled}
        label="Mode sombre"
        labelPosition="left"
      />
    </View>
  );
};

export const Sizes = () => {
  const [small, setSmall] = useState(false);
  const [medium, setMedium] = useState(true);
  const [large, setLarge] = useState(false);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <SwitchButton
        value={small}
        onValueChange={setSmall}
        label="Petit"
        size="small"
      />
      <SwitchButton
        value={medium}
        onValueChange={setMedium}
        label="Moyen (défaut)"
        size="medium"
      />
      <SwitchButton
        value={large}
        onValueChange={setLarge}
        label="Grand"
        size="large"
      />
    </View>
  );
};

export const Disabled = () => {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <SwitchButton
        value={false}
        onValueChange={() => {}}
        label="Désactivé (OFF)"
        disabled={true}
      />
      <SwitchButton
        value={true}
        onValueChange={() => {}}
        label="Désactivé (ON)"
        disabled={true}
      />
    </View>
  );
};

export const CustomColors = () => {
  const [isEnabled, setIsEnabled] = useState(true);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16, gap: 24 }}>
      <SwitchButton
        value={isEnabled}
        onValueChange={setIsEnabled}
        label="Couleurs personnalisées"
        colors={{
          active: '#FF6B6B',
          inactive: '#4ECDC4',
          thumb: '#FFE66D',
        }}
      />
    </View>
  );
};