/**
 * ProgressIndicator - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import { COLORS } from "../../../../constants";
import ProgressIndicator from "../index";

describe("ProgressIndicator Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<ProgressIndicator value={1} />).toJSON();
      expect(tree).toMatchSnapshot();
    });

  it(`should render with ${COLORS.success} color when value is 1`, () => {
    const { getByTestId } = render(<ProgressIndicator value={1} />);
    const progressBar = getByTestId('progressindicator');
    expect(progressBar.props.style[0].backgroundColor).toBe(COLORS.success);
  });

  it(`should render with ${COLORS.warning} color when value is lower than 0.5`, () => {
    const { getByTestId } = render(<ProgressIndicator value={0.4} />);
    const progressBar = getByTestId('progressindicator');
    expect(progressBar.props.style[0].backgroundColor).toBe(COLORS.warning);
  });

  it(`should render with ${COLORS.dangerLight} color when value is lower than 0.25`, () => {
    const { getByTestId } = render(<ProgressIndicator value={0.2} />);
    const progressBar = getByTestId('progressindicator');
    expect(progressBar.props.style[0].backgroundColor).toBe(COLORS.dangerLight);
  });
});