/**
 * GDateInput - Generated by Garanteasier CLI
 */

import { render } from "@testing-library/react-native";
import React from "react";
import GDateInput from "../index";

describe("GDateInput Components", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

    test('renders correctly', () => {
      const tree = render(<GDateInput label="Start Date" />).toJSON();
      expect(tree).toMatchSnapshot();
    });
});